version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq_network

  rmq-producer-api:
    build:
      context: .
      dockerfile: Rmq.Producer.Api/Dockerfile
    container_name: rmq-producer-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQSettings__Host=rabbitmq
      - RabbitMQSettings__VirtualHost=/
      - RabbitMQSettings__Username=guest
      - RabbitMQSettings__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network

  rmq-consumer-api:
    build:
      context: .
      dockerfile: Rmq.Consumer.Api/Dockerfile
    container_name: rmq-consumer-api
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQSettings__Host=rabbitmq
      - RabbitMQSettings__VirtualHost=/
      - RabbitMQSettings__Username=guest
      - RabbitMQSettings__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge 